/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:7e06574a-4681-4c91-888e-9600681508cd",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_3mY8Vpu52",
    "aws_user_pools_web_client_id": "k4a4bpq5n35pqrg0pjiop4lsk",
    "oauth": {}
};


export default awsmobile;
