/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fe507388-2d3f-4c1a-9054-8bf27dcdfb0f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_wdzf5AZfB",
    "aws_user_pools_web_client_id": "2ces9sg769o2kro9mpjjs0k4ti",
    "oauth": {}
};


export default awsmobile;
