/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fe507388-2d3f-4c1a-9054-8bf27dcdfb0f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_wdzf5AZfB",
    "aws_user_pools_web_client_id": "2ces9sg769o2kro9mpjjs0k4ti",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://26i6biwbcffrpcul54qhs6cjba.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vqyteudeq5bcvjhvwvkkx2zzde",
    "aws_user_files_s3_bucket": "bucket40954-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
